### PR TITLE
Split `go-ipfs/routing/kbucket` into `go-libp2p-kbucket`

### PR DESCRIPTION
**Pull request by geoah**
This PR splits `go-ipfs/routing/kbucket` from `go-ipfs` into `libp2p/go-libp2p-kbucket`

* Undoes gx rewrite
* Adds travis-ci
* Re-Adds `README` and `LICENCE` (messed up because of my graft)

There are two dependencies left to be handled for gx to work.

1. `go-ipfs/thirdparty/testutil` will be dealt with with the rest of the thirdparties.
2. `go-ipfs/routing/keyspace` I think could be moved in here as well. @whyrusleeping thoughts?

@whyrusleeping if can please enable travis for this repo.

Thanks :)

### CODE REVIEW

**Comment by whyrusleeping** [comment]
I think that the thirdparty testutil is duplicate code from go-libp2p/testutil, we might be able to handle both of those at the same time. Want me to make a repo for it?

The routing keyspace stuff can probably move in here, i believe this is the only place its used.

**Comment by whyrusleeping** [comment]
travis has been enabled

**Comment by geoah** [comment]
@whyrusleeping `keyspace` has been moved here, please make a new repo for `thirdparty/testutil` so we can get this over with once `go-key` is merged and published! :D

Thanks!

**Comment by whyrusleeping** [comment]
LGTM!

**Pull request merged**
